# Generated by Django 4.2.4 on 2023-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameroom_player1_alter_gameroom_player2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='board',
            field=models.CharField(blank=True, default='         ', max_length=9),
        ),
    ]
