# Generated by Django 4.2.4 on 2023-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_rename_gamemembers_gamemember'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='board',
            field=models.CharField(default='         ', max_length=9),
        ),
    ]
