# Generated by Django 4.2.4 on 2023-08-07 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_gameroom_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='board',
        ),
    ]
