# Generated by Django 4.2.4 on 2023-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_gameroom_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='board',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
