# Generated by Django 4.2.4 on 2023-08-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gameroom_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_state',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
