# Generated by Django 4.2.4 on 2023-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
