# Generated by Django 4.2.4 on 2023-08-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gameroom_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='is_completed',
            new_name='is_active',
        ),
    ]
