# Generated by Django 4.2.4 on 2023-08-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_is_completed_gameroom_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='is_active',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('1', 'Ожидание игрока'), ('2', 'В игре'), ('3', 'Игра окончена')], default=3, max_length=1),
            preserve_default=False,
        ),
    ]
