# Generated by Django 4.2.4 on 2023-08-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_gameroom_options_remove_gameroom_player1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameMembers',
            new_name='GameMember',
        ),
    ]
