# Generated by Django 4.2.4 on 2023-08-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_gameroom_options_alter_gameroom_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='board',
            field=models.JSONField(),
        ),
    ]
