# Generated by Django 4.2.4 on 2023-08-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gameroom_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Сложная')], default='easy', max_length=6),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='lives',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
