# Generated by Django 4.2.4 on 2023-08-10 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_gameroom_difficulty_gameroom_lives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='winner',
        ),
    ]
