# Generated by Django 4.2.4 on 2023-08-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_remove_gameroom_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='cells_remain',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('1', 'В игре'), ('2', 'Игра окончена')], max_length=1),
        ),
    ]
